//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Periotris.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Periotris.Net.Properties.MainWindowResources", typeof(MainWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutFlyoutHeader {
            get {
                return ResourceManager.GetString("AboutFlyoutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periotris.Net is a .NET 5 porting and modernized version of CSharperMantle&apos;s Periotris game belonging to CmTetris product family.
        ///
        ///
        ///
        ///Copyright (C) 2020-present Rong &quot;Mantle&quot; Bao (CSharperMantle)
        ///
        ///This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful, but [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutFlyoutText {
            get {
                return ResourceManager.GetString("AboutFlyoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string AssistanceGridModeDisabledCaption {
            get {
                return ResourceManager.GetString("AssistanceGridModeDisabledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string AssistanceGridModeEnabledCaption {
            get {
                return ResourceManager.GetString("AssistanceGridModeEnabledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance grid visibility:.
        /// </summary>
        public static string AssistanceGridModeHeader {
            get {
                return ResourceManager.GetString("AssistanceGridModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ColorModeDefaultCaption {
            get {
                return ResourceManager.GetString("ColorModeDefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color mode:.
        /// </summary>
        public static string ColorModeHeader {
            get {
                return ResourceManager.GetString("ColorModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorless.
        /// </summary>
        public static string ColorModeNoneCaption {
            get {
                return ResourceManager.GetString("ColorModeNoneCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on GitHub.
        /// </summary>
        public static string LaunchGitHubRepoButtonContent {
            get {
                return ResourceManager.GetString("LaunchGitHubRepoButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Periotris.NET repo in browser.
        /// </summary>
        public static string LaunchGitHubRepoButtonToolTip {
            get {
                return ResourceManager.GetString("LaunchGitHubRepoButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periotris.NET.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string MapPathOpenButtonContent {
            get {
                return ResourceManager.GetString("MapPathOpenButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom map path:.
        /// </summary>
        public static string MapPathOpenHeader {
            get {
                return ResourceManager.GetString("MapPathOpenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom map:.
        /// </summary>
        public static string MapPathToggleHeader {
            get {
                return ResourceManager.GetString("MapPathToggleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MapPathToggleOffContent {
            get {
                return ResourceManager.GetString("MapPathToggleOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MapPathToggleOnContent {
            get {
                return ResourceManager.GetString("MapPathToggleOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsFlyoutHeader {
            get {
                return ResourceManager.GetString("SettingsFlyoutHeader", resourceCulture);
            }
        }
    }
}
